inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;
detect-client-opacity = false;
corner-radius = 0;
backend = "glx";
vsync = false;
use-damage = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
log-level = "warn";
shadow = false;
fading = false;
animations = false;
